'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Layout from '@/components/Layout';
import Button from '@/components/Button';
import { useLanguage } from '@/contexts/LanguageContext';
import { useGame } from '@/contexts/GameContext';
import Link from 'next/link';

export default function Home() {
  const router = useRouter();
  const { t } = useLanguage();
  const { state, dispatch } = useGame();
  const { cases, gameState } = state;
  const [showResetConfirm, setShowResetConfirm] = useState(false);

  const activeCase = gameState.activeCase
    ? cases.find(c => c.id === gameState.activeCase)
    : null;

  const handleResetGame = () => {
    if (showResetConfirm) {
      // Reset the game state
      dispatch({ type: 'RESET_GAME' });
      // Reload the page to trigger loading sample cases
      window.location.reload();
    } else {
      setShowResetConfirm(true);
    }
  };

  return (
    <Layout>
      <div className="flex flex-col items-center justify-center py-8 md:py-16">
        <div className="text-center mb-8">
          <h1 className="text-5xl md:text-6xl font-black comic-text mb-6 text-center text-[var(--borderlands-yellow)] transform -rotate-1">
            {t('app.title')}
          </h1>
          <p className="text-lg md:text-xl mb-4 text-center font-bold comic-text text-white">
            {t('app.subtitle')}
          </p>
          <p className="text-md max-w-2xl mx-auto opacity-80">
            Experience a detective game powered by <a href="https://opentyphoon.ai" target="_blank" rel="noopener noreferrer" className="text-[var(--borderlands-yellow)] hover:underline">Typhoon AI</a>.
            This interactive demo showcases how large language models can create dynamic narratives,
            realistic character interactions, and adaptive gameplay.
          </p>
        </div>

        <div className="max-w-lg w-full">
          {activeCase ? (
            <div className="borderlands-panel flex flex-col gap-6 p-6 bg-surface-800 transform rotate-1">
              <h2 className="text-3xl font-black comic-text text-[var(--borderlands-yellow)]">{activeCase.title}</h2>
              <p className="opacity-80 font-bold">{activeCase.summary}</p>
              <div className="flex flex-col sm:flex-row gap-4 mt-4">
                <Button
                  variant="accent"
                  size="lg"
                  fullWidth
                  onClick={() => router.push('/cases/' + activeCase.id)}
                >
                  {t('game.continue')}
                </Button>
                <Button
                  variant="outline"
                  size="lg"
                  fullWidth
                  onClick={() => router.push('/cases')}
                >
                  {t('game.new_case')}
                </Button>
              </div>
            </div>
          ) : (
            <div className="borderlands-panel flex flex-col gap-6 p-6 bg-surface-800 transform -rotate-1">
              <h2 className="text-3xl font-black comic-text text-[var(--borderlands-yellow)]">{t('game.start')}</h2>
              <p className="opacity-80 font-bold">
                Start a new investigation and solve a detective case. Use your deduction skills to analyze clues, interview suspects, and solve the mystery.
              </p>
              <Button
                variant="accent"
                size="lg"
                fullWidth
                onClick={() => router.push('/cases')}
              >
                {t('game.start')}
              </Button>
            </div>
          )}

          {/* Game Features */}
          <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="borderlands-panel p-4 bg-surface-800 transform rotate-1">
              <h3 className="font-bold comic-text text-[var(--borderlands-orange)]">AI-Generated Cases</h3>
              <p className="text-sm opacity-80 mt-2">Each case is uniquely generated by Typhoon's LLM, creating endless possibilities.</p>
            </div>
            <div className="borderlands-panel p-4 bg-surface-800 transform -rotate-1">
              <h3 className="font-bold comic-text text-[var(--borderlands-orange)]">Dynamic Interviews</h3>
              <p className="text-sm opacity-80 mt-2">Interact with suspects through natural language conversations powered by AI.</p>
            </div>
            <div className="borderlands-panel p-4 bg-surface-800 transform -rotate-1">
              <h3 className="font-bold comic-text text-[var(--borderlands-orange)]">Intelligent Analysis</h3>
              <p className="text-sm opacity-80 mt-2">The AI analyzes clues to provide insights and help you solve the case.</p>
            </div>
            <div className="borderlands-panel p-4 bg-surface-800 transform rotate-1">
              <h3 className="font-bold comic-text text-[var(--borderlands-orange)]">Multilingual Support</h3>
              <p className="text-sm opacity-80 mt-2">Experience the game in multiple languages, showcasing Typhoon's versatility.</p>
            </div>
          </div>

          {/* Reset Game Button */}
          <div className="mt-10 text-center">
            <Button
              variant={showResetConfirm ? "accent" : "outline"}
              size="sm"
              onClick={handleResetGame}
              className={showResetConfirm ? "bg-[var(--borderlands-red)] text-white border-black" : "border-black"}
            >
              {showResetConfirm ? "Confirm Reset Game" : "Reset Game"}
            </Button>
            {showResetConfirm && (
              <p className="text-sm mt-2 text-[var(--borderlands-red)] font-bold comic-text">
                Warning: This will delete all your progress and start over with sample cases.
              </p>
            )}
          </div>

          {/* How to Play link */}
          <div className="mt-5 text-center">
            <Link href="/how-to-play" className="text-[var(--borderlands-yellow)] hover:text-[var(--borderlands-orange)] transition-colors font-bold comic-text">
              {t('nav.howToPlay') || 'How to Play'}
            </Link>
            <span className="mx-3 text-gray-500">|</span>
            <Link href="/how-it-works" className="text-[var(--borderlands-yellow)] hover:text-[var(--borderlands-orange)] transition-colors font-bold comic-text">
              {t('nav.howItWorks') || 'How It Works'}
            </Link>
            <span className="mx-3 text-gray-500">|</span>
            <a href="https://opentyphoon.ai" target="_blank" rel="noopener noreferrer" className="text-[var(--borderlands-yellow)] hover:text-[var(--borderlands-orange)] transition-colors font-bold comic-text">
              Learn About Typhoon AI
            </a>
          </div>

          <div className="mt-8 text-center text-xs text-gray-500">
            Powered by <a href="https://opentyphoon.ai" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-[var(--borderlands-yellow)]">Typhoon AI</a> models: typhoon-v2.1-12b-instruct & typhoon-v2-r1-70b-preview
          </div>
        </div>
      </div>
    </Layout>
  );
}
