import React from 'react';
import { FaRobot } from 'react-icons/fa6';

interface AIDisclaimerProps {
    className?: string;
    gtmId?: string;
}

export default function AIDisclaimer({ className = '', gtmId }: AIDisclaimerProps) {
    return (
        <div
            className={`text-xs bg-surface-800/80 border border-surface-700 rounded-md p-3 ${className}`}
            data-gtm-id={gtmId || "ai-disclaimer"}
        >
            <div className="flex items-start">
                <FaRobot className="text-gray-400 mt-1 mr-2 flex-shrink-0" />
                <p className="text-gray-400">
                    Disclaimer: The responses generated by this Artificial Intelligence (AI) system are autonomously constructed and do not necessarily reflect the views or positions of the developing organizations, their affiliates, or any of their employees. These AI-generated responses do not represent those of the organizations. The organizations do not endorse, support, sanction, encourage, verify, or agree with the comments, opinions, or statements generated by this AI. The information produced by this AI is not intended to malign any religion, ethnic group, club, organization, company, individual, anyone, or anything. It is not the intent of the organizations to malign any group or individual. The AI operates based on its programming and training data and its responses should not be interpreted as the explicit intent or opinion of the organizations.
                </p>
            </div>
        </div>
    );
} 